# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Проект\ui\new_item.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 343)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 20, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.id_party = QtWidgets.QLineEdit(Form)
        self.id_party.setGeometry(QtCore.QRect(140, 199, 131, 21))
        self.id_party.setObjectName("id_party")
        self.new_item = QtWidgets.QPushButton(Form)
        self.new_item.setGeometry(QtCore.QRect(40, 280, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_item.setFont(font)
        self.new_item.setObjectName("new_item")
        self.count = QtWidgets.QLineEdit(Form)
        self.count.setGeometry(QtCore.QRect(140, 160, 131, 21))
        self.count.setObjectName("count")
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setGeometry(QtCore.QRect(140, 110, 131, 21))
        self.price.setObjectName("price")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(140, 60, 131, 21))
        self.name.setObjectName("name")
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setGeometry(QtCore.QRect(140, 20, 131, 21))
        self.id.setObjectName("id")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.box = QtWidgets.QComboBox(Form)
        self.box.setGeometry(QtCore.QRect(150, 240, 131, 22))
        self.box.setObjectName("comboBox")
        self.box.addItem("")
        self.box.addItem("")
        self.box.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Наименование"))
        self.label_3.setText(_translate("Form", "Цена за штуку"))
        self.label_4.setText(_translate("Form", "Количество"))
        self.label_5.setText(_translate("Form", "ID партии"))
        self.new_item.setText(_translate("Form", "Добавить"))
        self.label_6.setText(_translate("Form", "Состояние"))
        self.box.setItemText(0, _translate("Form", "в наличие"))
        self.box.setItemText(1, _translate("Form", "продано"))
        self.box.setItemText(2, _translate("Form", "бронь"))
