from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt

def many_function(form):
    form.delete()

class MyTable(QtWidgets.QTableWidget):
    def __init__(self, form):
        super().__init__(form)
        self.form = form

    def keyPressEvent(self, event):
        try:
            if event.key() == Qt.Key_Delete:
                many_function(self.form)
        except Exception as e:
            print(e)


# Добавить состояния брони, в наличие, продано

class Main_ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1123, 845)
        self.main_table = MyTable(Form)
        self.main_table.setGeometry(QtCore.QRect(10, 40, 761, 791))
        self.main_table.setObjectName("main_table")
        self.main_table.setColumnCount(6)
        self.main_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.main_table.setHorizontalHeaderItem(5, item)
        self.new_elem = QtWidgets.QPushButton(Form)
        self.new_elem.setGeometry(QtCore.QRect(10, 10, 531, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_elem.setFont(font)
        self.new_elem.setObjectName("new_elem")
        self.showforkrit = QtWidgets.QPushButton(Form)
        self.showforkrit.setGeometry(QtCore.QRect(790, 40, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.showforkrit.setFont(font)
        self.showforkrit.setObjectName("showforkrit")
        self.error = QtWidgets.QLabel(Form)
        self.error.setGeometry(QtCore.QRect(800, 30, 301, 271))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.error.setFont(font)
        self.error.setObjectName("error")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.main_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "id"))
        item = self.main_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Наименование"))
        item = self.main_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Цена за штуку"))
        item = self.main_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Количество"))
        item = self.main_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Номер партии"))
        item = self.main_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Состояние"))
        self.new_elem.setText(_translate("Form", "Добавить"))
        self.showforkrit.setText(_translate("Form", "Показать по критерию"))
        self.error.setText(_translate("Form", "Ошибка!"))
        self.error.hide()


class NewItemUI(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(590, 343)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 20, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.id_party = QtWidgets.QLineEdit(Form)
        self.id_party.setGeometry(QtCore.QRect(140, 199, 131, 21))
        self.id_party.setObjectName("id_party")
        self.new_item = QtWidgets.QPushButton(Form)
        self.new_item.setGeometry(QtCore.QRect(40, 280, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_item.setFont(font)
        self.new_item.setObjectName("new_item")
        self.count = QtWidgets.QLineEdit(Form)
        self.count.setGeometry(QtCore.QRect(140, 160, 131, 21))
        self.count.setObjectName("count")
        self.price = QtWidgets.QLineEdit(Form)
        self.price.setGeometry(QtCore.QRect(140, 110, 131, 21))
        self.price.setObjectName("price")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(140, 60, 131, 21))
        self.name.setObjectName("name")
        self.id = QtWidgets.QLineEdit(Form)
        self.id.setGeometry(QtCore.QRect(140, 20, 131, 21))
        self.id.setObjectName("id")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 240, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.box = QtWidgets.QComboBox(Form)
        self.box.setGeometry(QtCore.QRect(150, 240, 131, 22))
        self.box.setObjectName("comboBox")
        self.box.addItem("")
        self.box.addItem("")
        self.box.addItem("")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Наименование"))
        self.label_3.setText(_translate("Form", "Цена за штуку"))
        self.label_4.setText(_translate("Form", "Количество"))
        self.label_5.setText(_translate("Form", "ID партии"))
        self.new_item.setText(_translate("Form", "Добавить"))
        self.label_6.setText(_translate("Form", "Состояние"))
        self.box.setItemText(0, _translate("Form", "в наличие"))
        self.box.setItemText(1, _translate("Form", "продано"))
        self.box.setItemText(2, _translate("Form", "бронь"))

class CritUi(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1073, 851)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(10, 10, 611, 821))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.criteti = QtWidgets.QComboBox(Form)
        self.criteti.setGeometry(QtCore.QRect(640, 30, 131, 31))
        self.criteti.setObjectName("criteti")
        self.criteti.addItem('id')
        self.criteti.addItem('Название')
        self.criteti.addItem('Цена')
        self.criteti.addItem('Кол-во')
        self.criteti.addItem('Партия')
        self.criteti.addItem('Состояние')
        self.text_crit = QtWidgets.QLineEdit(Form)
        self.text_crit.setGeometry(QtCore.QRect(780, 30, 241, 31))
        self.text_crit.setObjectName("text_crit")
        self.show_it = QtWidgets.QPushButton(Form)
        self.show_it.setGeometry(QtCore.QRect(900, 80, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.show_it.setFont(font)
        self.show_it.setObjectName("show_it")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.show_it.setText(_translate("Form", "Показать"))